### PR TITLE
UP devops k8s jacloud

### PR DESCRIPTION
**Pull request by sandisunandar99**
## Overview 

1. UP k8s to Production
2. some feature get up to prod

_**notes :**_
info to user before server down,, :laughing:

### CODE REVIEW

**Comment by firmanJS** [comment]
branch codeclimate up ke prod juga ga mang @sandisunandar99 ?

**Comment by sandisunandar99** [comment]
> branch codeclimate up ke prod juga ga mang @sandisunandar99 ?

boleh2,, nu mana wae nu rek di up ka prod?

**Comment by firmanJS** [comment]
nu week5 task1 - task3

**Comment by firmanJS** [comment]
> > branch codeclimate up ke prod juga ga mang @sandisunandar99 ?
> 
> boleh2,, nu mana wae nu rek di up ka prod?

nu week5 task1 - task3

**Comment by sandisunandar99** [comment]
> > > branch codeclimate up ke prod juga ga mang @sandisunandar99 ?
> > 
> > 
> > boleh2,, nu mana wae nu rek di up ka prod?
> 
> nu week5 task1 - task3

okay2,, sya bkin hela PR na

**Review by firmanJS — APPROVED** [review]

**Review by smilelikeshit — APPROVED** [review]
gas mang

**Comment by sandisunandar99** [comment]
> gas mang

sudah up

**Comment by firmanJS** [comment]
down baraha menit ?

**Pull request merged**
