### PR TITLE
handler core hapi

### PR DESCRIPTION
**Pull request by firmanJS**
##OVERVIEW

handler error in core hapi reply interface called twice ref : https://stackoverflow.com/questions/41993642/hapijs-reply-being-called-twice

### CODE REVIEW

**Comment by firmanJS** [comment]
up @sandisunandar99 @khihadysucahyo

**Review by sandisunandar99 — APPROVED** [review]
gas

**Comment by sandisunandar99** [comment]
@khihadysucahyo

**Comment by sandisunandar99** [comment]
need to megre now @firmanJS ?? wkwk

**Comment by firmanJS** [comment]
> need to megre now @firmanJS ?? wkwk

yes please merge for handler sentry error `reply interface`

**Pull request merged**
