### PR TITLE
Add github action sentry release workflow

### PR DESCRIPTION
**Pull request by yohang88**
Add github action sentry release workflow for adding version info on deployment.

https://docs.sentry.io/product/releases/
https://github.com/marketplace/actions/sentry-release

Gasss gasss.

### CODE REVIEW

**Review by sandisunandar99 — APPROVED** [review]
mantap,, nuhun2 mas @yohang88 ,,

**Review by firmanJS — APPROVED** [review]

**Comment by firmanJS** [comment]
> mantap,, nuhun2 mas @yohang88 ,,

English dude @sandisunandar99 🤣

**Comment by yohang88** [comment]
Gass gass please merge & deploy @sandisunandar99 @firmanJS 😂

**Comment by sandisunandar99** [comment]
> > mantap,, nuhun2 mas @yohang88 ,,
> 
> English dude @sandisunandar99 🤣 

Revenge 🤣

**Pull request merged**
