### PR TITLE
trying refactor local transmission

### PR DESCRIPTION
**Pull request by firmanJS**
### OVERVIEW

1. change rate D, C to A
1. minor 8 next improve code quality

### CODE REVIEW

**Comment by sandisunandar99** [comment]
codeclimate ieu mang.. eta benerken hela isu na.. wkwkkwkw

**Comment by firmanJS** [comment]
> codeclimate ieu mang.. @firmanJS eta benerken hela isu na.. wkwkkwkw

minor mang next eta mah soalna teu aya hubungan na sama file nu di ubah ku ana wkwkwk

**Comment by sandisunandar99** [comment]
> > codeclimate ieu mang.. @firmanJS eta benerken hela isu na.. wkwkkwkw
> 
> minor mang next eta mah soalna teu aya hubungan na sama file nu di ubah ku ana wkwkwk

oh wkwkwkwk okay2

**Review by sandisunandar99 — APPROVED** [review]

**Review by khihadysucahyo — APPROVED** [review]

**Comment by khihadysucahyo** [comment]
@firmanJS branchnya dihapus ga kang?

**Pull request merged**
